INSERT INTO PRODUTOS VALUES (1, 'Notebook', 'Eletrônicos', 1500);
INSERT INTO CLIENTES VALUES (1, 'Maria', 'Nordeste');
INSERT INTO VENDAS VALUES (1, 1, TO_DATE('2025-01-01', 'YYYY-MM-DD'), 'Online');
INSERT INTO ITENS_VENDA VALUES (1, 1, 2, 2500);
