CREATE TABLE PRODUTOS (
  ID_PRODUTO NUMBER PRIMARY KEY,
  NOME_PRODUTO VARCHAR2(100),
  CATEGORIA VARCHAR2(50),
  PRECO_CUSTO NUMBER
);

CREATE TABLE CLIENTES (
  ID_CLIENTE NUMBER PRIMARY KEY,
  NOME_CLIENTE VARCHAR2(100),
  REGIAO VARCHAR2(50)
);

CREATE TABLE VENDAS (
  ID_VENDA NUMBER PRIMARY KEY,
  ID_CLIENTE NUMBER,
  DATA_VENDA DATE,
  CANAL_VENDA VARCHAR2(50)
);

CREATE TABLE ITENS_VENDA (
  ID_VENDA NUMBER,
  ID_PRODUTO NUMBER,
  QUANTIDADE NUMBER,
  PRECO_UNITARIO_VENDA NUMBER
);
